### PR TITLE
Added repr for 2 classes

### PR DESCRIPTION
**Pull request by NarayanAdithya**
# Added __repr__ to TheoreticalSemiVariogram and Krige Classes

## Description
Added `__rep__()` for 2 classes

## Problem
Why this is a problem? How it affects users?

## Solution
Describe solution for the presented problem.

### Affected modules
- TheoreticalSemiVariogram Class
- Krige Class

### Package check

- [ ] All tests passed
- [ ] Documentation updated
- [ ] All tutorials are working properly

Solves #175

### CODE REVIEW

**Comment by NarayanAdithya** [comment]
Hey @szymon-datalions I will fix the issues as soon as possible.

**Comment by szymon-datalions** [comment]
> Hey @szymon-datalions I will fix the issues as soon as possible.

Thanks! :)

**Comment by szymon-datalions** [comment]
> Hey @szymon-datalions I will fix the issues as soon as possible.

Hi @NarayanAdithya ! I don't know if you've fixed issues but a part: 
```And one more thing, but it's my problem: argument name is points_array but the class has internal argument self.points_values. It is very misleading and I'm creating a new issue related to this problem, but you should remember about this convention in the __repr__()``` 

is no longer important. In the newest commits within `dev` and `main` branches argument is renamed to `points_array` :)

So only the initialization thing is now essential.

**Comment by NarayanAdithya** [comment]
Hey, @szymon-datalions  Sorry for the delay, I was not able to check in because of my academic work. I am trying to fix the issue, but I can't get the environment setup. When i run pip install I am getting the following error:

```
Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Pull request merged**
